version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t mu_repo .
      - docker tag mu_repo:latest 486790186775.dkr.ecr.us-east-2.amazonaws.com/mu_repo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 486790186775.dkr.ecr.us-east-2.amazonaws.com/mu_repo:latest
artifacts:
  files:
    - '**/*'
  discard-paths: no