version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python tests/flaskblog_unit_test.py -v
artifacts:
  files:
    - '**/*'
  discard-paths: no